# Generated by Django 2.0 on 2018-09-14 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer_user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='unnamed')),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('bust', models.FloatField(null=True)),
                ('waist', models.FloatField(null=True)),
                ('hips', models.FloatField(null=True)),
                ('shoulder', models.FloatField(null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('metric_length', models.CharField(choices=[('cm', 'cm'), ('in', 'in')], default='cm', max_length=2)),
                ('metric_weight', models.CharField(choices=[('kg', 'kg'), ('lb', 'lb')], default='kg', max_length=2)),
                ('skin', models.CharField(choices=[('dark', 'dark'), ('light', 'light')], default='light', max_length=5)),
                ('body_shape', models.CharField(choices=[['Hourglass body shape', 'Hourglass body shape'], ['Oval Body shape', 'Oval Body shape'], ['Pear body shape with a bit tummy fat.', 'Pear body shape with a bit tummy fat.'], ['Rectangle Body shape', 'Rectangle Body shape'], ['Rectangle Body shape with a bit tummy fat.', 'Rectangle Body shape with a bit tummy fat.'], ['inverted triangle Body shape', 'inverted triangle Body shape'], ['inverted triangle Body shape with a bit tummy fat.', 'inverted triangle Body shape with a bit tummy fat.'], ['inverted triangle body shape with a bit tummy fat.', 'inverted triangle body shape with a bit tummy fat.'], ['pear Body shape', 'pear Body shape'], ['trapazod', 'trapazod'], ['triangle Body shape', 'triangle Body shape'], ['triangle body shape with a bit tummy fat.', 'triangle body shape with a bit tummy fat.']], max_length=50)),
                ('top_size', models.CharField(choices=[['5X - 22 US - 26 UK', '5X - 22 US - 26 UK'], ['4XL', '4XL'], ['S 40', 'S 40'], ['XS', 'XS'], ['M - 8 US - 12 UK', 'M - 8 US - 12 UK'], ['5XL', '5XL'], ['XL 50', 'XL 50'], ['Xl 52', 'Xl 52'], ['S', 'S'], ['XXS', 'XXS'], ['XS - 34', 'XS - 34'], ['S - 2 US - 6 UK', 'S - 2 US - 6 UK'], ['L 48', 'L 48'], ['M 42', 'M 42'], ['L - 10 US - 14 UK', 'L - 10 US - 14 UK'], ['L - 12 US - 16 UK ', 'L - 12 US - 16 UK '], ['L', 'L'], ['XXS - 00 US', 'XXS - 00 US'], ['XS - 0 US - 4 UK', 'XS - 0 US - 4 UK'], ['M 44', 'M 44'], ['M', 'M'], ['XS - 36', 'XS - 36'], ['XL - 14 US - 18 UK', 'XL - 14 US - 18 UK'], ['3X - 18 US - 22 UK', '3X - 18 US - 22 UK'], ['4Xl 58', '4Xl 58'], ['5Xl 60', '5Xl 60'], ['XL', 'XL'], ['M - 6 US - 10 UK', 'M - 6 US - 10 UK'], ['3Xl 56', '3Xl 56'], ['XXL', 'XXL'], ['XXl 54', 'XXl 54'], ['4X - 20 US - 24 UK', '4X - 20 US - 24 UK'], ['S 38', 'S 38'], ['S - 4 US - 8 UK', 'S - 4 US - 8 UK'], ['L 46', 'L 46'], ['2X - 16 US - 20 UK', '2X - 16 US - 20 UK'], ['3XL', '3XL']], max_length=18)),
                ('bottom_size', models.CharField(choices=[['5X - 22 US - 26 UK', '5X - 22 US - 26 UK'], ['4XL', '4XL'], ['S 40', 'S 40'], ['XS', 'XS'], ['M - 8 US - 12 UK', 'M - 8 US - 12 UK'], ['5XL', '5XL'], ['XL 50', 'XL 50'], ['Xl 52', 'Xl 52'], ['S', 'S'], ['XXS', 'XXS'], ['XS - 34', 'XS - 34'], ['S - 2 US - 6 UK', 'S - 2 US - 6 UK'], ['L 48', 'L 48'], ['M 42', 'M 42'], ['L - 10 US - 14 UK', 'L - 10 US - 14 UK'], ['L - 12 US - 16 UK ', 'L - 12 US - 16 UK '], ['L', 'L'], ['XXS - 00 US', 'XXS - 00 US'], ['XS - 0 US - 4 UK', 'XS - 0 US - 4 UK'], ['M 44', 'M 44'], ['M', 'M'], ['XS - 36', 'XS - 36'], ['XL - 14 US - 18 UK', 'XL - 14 US - 18 UK'], ['3X - 18 US - 22 UK', '3X - 18 US - 22 UK'], ['4Xl 58', '4Xl 58'], ['5Xl 60', '5Xl 60'], ['XL', 'XL'], ['M - 6 US - 10 UK', 'M - 6 US - 10 UK'], ['3Xl 56', '3Xl 56'], ['XXL', 'XXL'], ['XXl 54', 'XXl 54'], ['4X - 20 US - 24 UK', '4X - 20 US - 24 UK'], ['S 38', 'S 38'], ['S - 4 US - 8 UK', 'S - 4 US - 8 UK'], ['L 46', 'L 46'], ['2X - 16 US - 20 UK', '2X - 16 US - 20 UK'], ['3XL', '3XL']], max_length=18)),
                ('customer', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to='customers.Customer')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together={('name', 'height', 'weight', 'bust', 'waist', 'shoulder', 'hips', 'gender', 'metric_length', 'metric_weight'), ('customer', 'name')},
        ),
    ]
